### ISSUE TITLE
add support for Laravel 9

### ISSUE THREAD

**Issue by eminos** [agence-webup/laravel-sendinblue#55]

**Comment by vorban** [comment]
There is currently no plan to support Laravel 9.

Feel free to submit a pull request :)

**Comment by nicolus** [comment]
@eminos : I don't think we actually need to add Laravel 9 support to this project.

Laravel already supports Symfony Mailer Transports, and there's a Transport for Sendinblue. It's even the example they used in the documentation : https://laravel.com/docs/9.x/mail#additional-symfony-transports

**Comment by vorban** [comment]
To clarify, does Laravel 9 with Sendinblue work "out of the box", or do you mean that our package works "flawlessly" on Laravel 9 ?

**Comment by nicolus** [comment]
Laravel 9 with sendinblue works almost "out of the box" with the steps described in the Laravel documentation linked above.

It's not really "out of the box" since you have to require the `symfony/sendinblue-mailer` package, but since Laravel 9 relies on Symfony Mailer, I think it makes sense to use the first party transports from Symfony Mailer.

**Comment by amenk** [comment]
Does not seem to fully work :-(

```
Class "Illuminate\Mail\Transport\Transport" not found {"exception":"[object] (Error(code: 0): Class \"Illuminate\\Mail\\Transport\\Transport\" not found at /var/www/html/example/web/vendor/webup/laravel-sendinblue/src/SendinBlueTransport.php:20)
```

I guess we will try to look into it.

**Comment by kolaente** [comment]
We ended up using the Symfony sendinblue package as described in the docs: https://laravel.com/docs/9.x/mail#additional-symfony-transports

That seems to work pretty good.

**Comment by aldozumaran** [comment]
@kolaente how can i pass the templateId and params?

**Comment by nicolus** [comment]
@aldozumaran : I don't think you can. I actually didn't realize that this package also allowed you to use sendinblue templates, as I only use it as an SMTP service to send transactional e-mails built from blade views. I suspect this is @kolaente 's usecase too, and what is covered by the sendinblue transport that's described in the docs.

I think it would make more sense to have a separate package that only handles sending templates through the sendinblue API.

**Comment by vorban** [comment]
The initial goal of this package was to wrap the official V3 SDK for Laravel **because at the time it wasn't supported as a mail transport**, and it has allowed us to use the mailable syntax in our projects, among other things.

With Laravel 9's out of the box support for SiB's basic transactional emails, it does seem like our package is out of league with what the Laravel team is currently providing and what it will be able to provide long-term.

We focused on SiB's template system because that was our primary usage of SiB at that time. Since then, some things have changed, and as far as I'm aware, we are are no longer using it as part of our current commercial projects. This means that we haven't got much time dedicated to update the package.

Even though Laravel does not support SiB's template system yet (perhaps _won't ever_), doing things the official way has always been "the right way" with Laravel.

SiB templating system is growing, last time I checked batch mailing was in the works. Our package is trying to force the API into a Laravel Transport, but it doesn't really match the reality: this part of SIB is less of a mail transport and more of an API that happens to send mails (ex: batch, tags, templates, customer syncing, marketing data, etc).

With that in mind, I agree with @nicolus and would recommend you to :
- Use Laravel 9's official support for SendInBlue transactional emails
- Use SendInBlue's Official SDK v3 for anything else.

We maintain this package as much as we can, but Laravel will outclass what we can provide 😃 .

**Comment by dostrog** [comment]
@aldozumaran @nicolus 

You can use laravel9 new Symfony mail transport for sendinblue and also can use extra params. For example (in Mailable):

```
    public function build(): self
    {

        $this->withSymfonyMessage(static function ($message) {
            $message->getHeaders()
                ->addTextHeader('templateId', 3)
                ->addParameterizedHeader('params', 'params', [
                    'PARAM1' => 'param1',
                ]);
        });

        return $this
            ->view('emails.form.question')
            ->with(['data' => $this->questionFormData]);
    }

```

**Comment by dostrog** [comment]
@aldozumaran @nicolus 

you can use Laravel9 with symfony mail transport and set extra params as well. For example in your Mailable:

```
    public function build(): self
    {

        $this->view('emails.form.question')->with(['data' => $this->questionFormData]);

        $this->withSymfonyMessage(function (Email $message) {
                $message->getHeaders()
                    ->addHeader('templateId', 3)
                    ->addParameterizedHeader('params', 'params', [
                        'FULL_NAME' => $this->questionFormData['full_name'] ?? '',
                        'MESSAGE' => $this->questionFormData['message'] ?? '',
                    ]);
            });

        return $this;
    }

```
