### ISSUE TITLE
What is the difference between SENDINBLUE_KEY_IDENTIFIER and SENDINBLUE_KEY and where to find them on sendinblue website

### ISSUE THREAD

**Issue by mgouguasse** [agence-webup/laravel-sendinblue#64]
I am already using sendinblue smtp with laravel to send emails, and i am now workin on adding tags to my emails, so i used this package 
but i have  some difficulties to setup the configuration in config/services.php so i have some questions:
1) where to find SENDINBLUE_KEY_IDENTIFIER  and SENDINBLUE_KEY on sendingblue website.
2)Should i change the env file that looks like  :
MAIL_MAILER=smtp
MAIL_DRIVER=smtp
MAIL_HOST=smtp-relay.sendinblue.com
MAIL_PORT=587
MAIL_USERNAME=test@mail.net
MAIL_PASSWORD=xxxxxxxxxxx
MAIL_ENCRYPTION=TLS
MAIL_FROM_ADDRESS=mail@mail.com
MAIL_FROM_NAME="${APP_NAME}"

**Comment by vorban** [comment]
If I'm not mistaken, the readme file holds all the info you need.

## 1. The env keys
When we send a request to SiB's API, it needs something like `{ jsonKey: 'my-api-key' }`. But because the `jsonKey` is not the same accross versions of the API, we allow users to configure it in the env.

So, the `SENDINBLUE_KEY_IDENTIFIER` is either `api-key` or `partner-key`, and `SENDINBLUE_KEY` is your actual API key given by SiB (available in your account settings on their website).

In the end, the request sent may look like `{ api-key: 'MY_API_KEY_1234' }`.

## 2. The regular env variables

You do not need to modify the other variables in any way.
Sendinblue is not a regular SMTP provider. Our package is a simple wrapper around the actual SiB API package, so in the actual networking is handled by the SiB package (over HTTP).

Per our readme, the instructions are clear:
```.env
MAIL_MAILER=sendinblue
SENDINBLUE_KEY=your-access-key

# if you need to set the guzzle proxy config
# those are example values
HTTP_PROXY="tcp://localhost:8125"
HTTPS_PROXY="tcp://localhost:9124"
NO_PROXY=.mit.edu,foo.com
```

I hope this helps you, I apologize for the delay.
